# Uncomment the next line to define a global platform for your project
# platform :ios, '13.0'

target 'FB' do
  use_frameworks!

pod 'Firebase/Core'
pod 'Firebase/Auth'
pod 'Firebase/Database'

pod 'JGProgressHUD'

pod 'MessageKit'

pod 'CryptoSwift'

end
